In [1]:
import numpy as np
np.__version__

'1.14.3'

In [20]:
test1 = np.random.randn(1000)
#test1

In [21]:
%timeit np.mean(test1)

7.04 µs ± 37.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
%timeit sum(test1)/len(test1)

72.5 µs ± 102 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [23]:
72.5/7.04

10.298295454545455

In [26]:
np.mean(test1) >= (sum(test1)/len(test1))

True

In [27]:
def mymean(data):
    sum = 0
    count = 0
    for dat in data:
        sum += dat
        count += 1
    return sum/count

In [28]:
%timeit mymean(test1)

116 µs ± 53.1 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [37]:
mymean(test1) == sum(test1)/len(test1)

True

In [38]:
105/7.32

14.344262295081966

In [29]:
import math

In [30]:
%timeit sum(test1)

72.1 µs ± 154 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [31]:
%timeit math.fsum(test1)

69.6 µs ± 135 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [32]:
%timeit np.sum(test1)

2.93 µs ± 19 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [33]:
sum(test1)

-30.939807608922507

In [34]:
math.fsum(test1)

-30.93980760892249

In [35]:
np.sum(test1)

-30.93980760892249

In [36]:
sum(test1)-math.fsum(test1)

-1.7763568394002505e-14

In [37]:
math.fsum(test1) - np.sum(test1)

0.0

**Creating arrays**

In [40]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [44]:
np.arange(1,5)

array([1, 2, 3, 4])

In [46]:
np.arange(1.,5)

array([1., 2., 3., 4.])

In [47]:
np.arange(1, 5) == np.arange(1., 5)

array([ True,  True,  True,  True])

In [54]:
test = np.arange(5)

In [50]:
np.arange(1, 5).dtype

dtype('int64')

In [51]:
np.arange(1., 5).dtype

dtype('float64')

In [58]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [59]:
np.zeros((10, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [60]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [61]:
np.array(range(0, 20, 2))

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [55]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
np.full((3, 5), 'hello')

array([['hello', 'hello', 'hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello', 'hello', 'hello']], dtype='<U5')

** Data types **

| Data type     | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)|
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)|
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)|
| ``int8``      | Byte (-128 to 127)|
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)|
| ``uint8``     | Unsigned integer (0 to 255)|
| ``uint16``    | Unsigned integer (0 to 65535)|
| ``uint32``    | Unsigned integer (0 to 4294967295)|
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)|
| ``float_``    | Shorthand for ``float64``.|
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa|
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa|
| ``complex_``  | Shorthand for ``complex128``.|
| ``complex64`` | Complex number, represented by two 32-bit floats|
| ``complex128``| Complex number, represented by two 64-bit floats|

In [39]:
np.random?

Type:        module
String form: <module 'numpy.random' from '/usr/global/Anaconda3-5.1.0/envs/jupyterlab/lib/python3.6/site-packages/numpy/random/__init__.py'>
File:        /usr/global/Anaconda3-5.1.0/envs/jupyterlab/lib/python3.6/site-packages/numpy/random/__init__.py
Docstring:  
Random Number Generation

==================== =========================================================
Utility functions
random_sample        Uniformly distributed floats over ``[0, 1)``.
random               Alias for `random_sample`.
bytes                Uniformly distributed random bytes.
random_integers      Uniformly distributed integers in a given range.
permutation          Randomly permute a sequence / generate a random sequence.
shuffle              Randomly permute a sequence in place.
seed                 Seed the random number generator.
choice               Random sample from 1-D array.

==================== =========================================================

==================== =====

In [68]:
np.random.random((3,3))

array([[0.33966992, 0.47760629, 0.20039104],
       [0.56625591, 0.94711808, 0.28454406],
       [0.08112652, 0.13539006, 0.47081288]])

In [69]:
np.random.normal(0, 1, (3, 3))

array([[ 0.07431999, -1.46365937, -1.92080596],
       [ 0.98826472,  0.21902753, -0.46514425],
       [ 1.07211069,  0.03930181,  0.67881311]])

In [71]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

If positive, int_like or int-convertible arguments are provided,
`randn` generates an array of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1 (if any of the :math:`d_i` are
floats, they are first converted to integers by truncation). A single
float randomly sampled from the distribution is returned if no
argument is provided.

This is a convenience function.  If you want an interface that takes a
tuple as the first argument, use `numpy.random.standard_normal` instead.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, should be all positive.
    If no argument is given a single Python float is returned.

Returns
-------
Z : ndarray or float
    A ``(d0, d1, ..., dn)``-shaped array of floating-point samples from
    the standard normal distributio

In [43]:
np.random.standard_normal?

Docstring:
standard_normal(size=None)

Draw samples from a standard Normal distribution (mean=0, stdev=1).

Parameters
----------
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.

Returns
-------
out : float or ndarray
    Drawn samples.

Examples
--------
>>> s = np.random.standard_normal(8000)
>>> s
array([ 0.6888893 ,  0.78096262, -0.89086505, ...,  0.49876311, #random
       -0.38672696, -0.4685006 ])                               #random
>>> s.shape
(8000,)
>>> s = np.random.standard_normal(size=(3, 4, 2))
>>> s.shape
(3, 4, 2)
Type:      builtin_function_or_method


In [42]:
np.random.seed?

Docstring:
seed(seed=None)

Seed the generator.

This method is called when `RandomState` is initialized. It can be
called again to re-seed the generator. For details, see `RandomState`.

Parameters
----------
seed : int or 1-d array_like, optional
    Seed for `RandomState`.
    Must be convertible to 32 bit unsigned integers.

See Also
--------
RandomState
Type:      builtin_function_or_method


In [74]:
np.random.seed(123)
test1 = np.random.randn(1000)
np.random.seed(123)
test2 = np.random.standard_normal(1000)
np.random.seed(123)
test3 = np.random.normal(0, 1, 1000)
np.all(test1 == test2) and np.all(test1 == test3)

True

In [67]:
np.random.randint(0, 10, (3, 3))

array([[0, 9, 6],
       [7, 3, 8],
       [8, 3, 9]])

In [81]:
test = np.empty(3)
test.fill(np.nan)
test[:2] = 2
np.nanmean(test)

2.0

In [85]:
test = np.ones(10, np.int)
test[0] = np.nan

ValueError: cannot convert float NaN to integer

In [91]:
test = ['hello', 1, 1.8, 'test']
np.array(test)

array(['hello', '1', '1.8', 'test'], dtype='<U5')

In [92]:
x = np.random.randint(10, size=(3, 4, 5)) # 3D array

In [70]:
x.ndim

3

In [71]:
x.shape

(3, 4, 5)

In [72]:
x.size

60

In [73]:
x.dtype

dtype('int64')

In [93]:
x.itemsize

8

In [94]:
x.nbytes

480

In [95]:
x

array([[[0, 9, 6, 7, 3],
        [8, 8, 3, 9, 0],
        [3, 2, 8, 0, 5],
        [6, 1, 7, 1, 3]],

       [[2, 8, 8, 1, 7],
        [7, 8, 6, 8, 3],
        [4, 6, 3, 8, 3],
        [8, 2, 6, 9, 3]],

       [[8, 0, 0, 8, 2],
        [2, 0, 5, 9, 1],
        [3, 1, 7, 3, 3],
        [3, 9, 5, 1, 8]]])

In [96]:
x[0, 0, 0] = 11

In [97]:
x

array([[[11,  9,  6,  7,  3],
        [ 8,  8,  3,  9,  0],
        [ 3,  2,  8,  0,  5],
        [ 6,  1,  7,  1,  3]],

       [[ 2,  8,  8,  1,  7],
        [ 7,  8,  6,  8,  3],
        [ 4,  6,  3,  8,  3],
        [ 8,  2,  6,  9,  3]],

       [[ 8,  0,  0,  8,  2],
        [ 2,  0,  5,  9,  1],
        [ 3,  1,  7,  3,  3],
        [ 3,  9,  5,  1,  8]]])

In [102]:
x[0, 0, 0] = '4' #3.14159    # this will be truncated!

In [105]:
np.int('3')

3

In [112]:
start = 0
stop = len(x)
step = 1
x[start:stop:step] # defaults: 0, size of dim, 1
x[:5] # first five elements
x[5:] # elements after index 5
x[4:7] # middle sub-array
x[::2] # every other element
x[1::2] # every other element, starting at index 1
x[::-1] # all elements, reversed
x[5::-2] # reversed every other from index 5
x[:2, :3] # two rows, three columns
x[:3, ::2] # three rows, every other column
x[::-1, ::-1] # reverse rows and columns

array([[[  8,   8,   3,   9,   5],
        [  3,   7,   3,   0,   5],
        [  5,   6,   7,   7,   3],
        [  1,   6,   0,   8,   6]],

       [[  5,   6,   5,   0,   3],
        [  1,   2,   2,   1,   5],
        [  9,   8,   9,   1,   2],
        [  4,   9, 888,   7,   4]],

       [[  7,   4,   3,   5,   5],
        [  1,   7,   1,   2,   0],
        [  3,   4,   2,   7,   1],
        [  3,   4,   5,   9,   6]]])

In [106]:
x[..., 2:4:2]  # start:stop:step
x[:, :, 2:4:2]

array([[[6],
        [3],
        [8],
        [7]],

       [[8],
        [6],
        [3],
        [6]],

       [[0],
        [5],
        [7],
        [5]]])

In [107]:
x_sub = x[:2, :2]

In [108]:
x_sub

array([[[4, 9, 6, 7, 3],
        [8, 8, 3, 9, 0]],

       [[2, 8, 8, 1, 7],
        [7, 8, 6, 8, 3]]])

In [109]:
x_sub[1, 0, 2] = 888

In [110]:
x_sub

array([[[  4,   9,   6,   7,   3],
        [  8,   8,   3,   9,   0]],

       [[  2,   8, 888,   1,   7],
        [  7,   8,   6,   8,   3]]])

In [111]:
x

array([[[  4,   9,   6,   7,   3],
        [  8,   8,   3,   9,   0],
        [  3,   2,   8,   0,   5],
        [  6,   1,   7,   1,   3]],

       [[  2,   8, 888,   1,   7],
        [  7,   8,   6,   8,   3],
        [  4,   6,   3,   8,   3],
        [  8,   2,   6,   9,   3]],

       [[  8,   0,   0,   8,   2],
        [  2,   0,   5,   9,   1],
        [  3,   1,   7,   3,   3],
        [  3,   9,   5,   1,   8]]])

In [112]:
x_sub_copy = x[:2, :2].copy()

In [113]:
x_sub_copy

array([[[  4,   9,   6,   7,   3],
        [  8,   8,   3,   9,   0]],

       [[  2,   8, 888,   1,   7],
        [  7,   8,   6,   8,   3]]])

In [114]:
x_sub_copy[1, 0, 2] = 777

In [115]:
x_sub_copy

array([[[  4,   9,   6,   7,   3],
        [  8,   8,   3,   9,   0]],

       [[  2,   8, 777,   1,   7],
        [  7,   8,   6,   8,   3]]])

In [116]:
x

array([[[  4,   9,   6,   7,   3],
        [  8,   8,   3,   9,   0],
        [  3,   2,   8,   0,   5],
        [  6,   1,   7,   1,   3]],

       [[  2,   8, 888,   1,   7],
        [  7,   8,   6,   8,   3],
        [  4,   6,   3,   8,   3],
        [  8,   2,   6,   9,   3]],

       [[  8,   0,   0,   8,   2],
        [  2,   0,   5,   9,   1],
        [  3,   1,   7,   3,   3],
        [  3,   9,   5,   1,   8]]])

| Operator      | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

| Operator      | Equivalent ufunc    || Operator      | Equivalent ufunc    |
|---------------|---------------------||---------------|---------------------|
|``==``         |``np.equal``         ||``!=``         |``np.not_equal``     |
|``<``          |``np.less``          ||``<=``         |``np.less_equal``    |
|``>``          |``np.greater``       ||``>=``         |``np.greater_equal`` |

| Operator      | Equivalent ufunc    || Operator      | Equivalent ufunc    |
|---------------|---------------------||---------------|---------------------|
|``&``          |``np.bitwise_and``   ||&#124;         |``np.bitwise_or``    |
|``^``          |``np.bitwise_xor``   ||``~``          |``np.bitwise_not``   |

** Broadcasting **

![Broadcasting Visual](figures/broadcasting.png)

1. If the two arrays differ in their number of dimensions, the
shape of the one with fewer dimensions is padded with ones
on its leading (left) side.
1. If the shape of the two arrays does not match in any
dimension, the array with shape equal to 1 in that dimension
is stretched to match the other shape.
1. If in any dimension the sizes disagree and neither is equal to
1, an error is raised.


Assignments
- Create a 10 × 2 array with random values. Assume these
are cartesian coordinates and convert them to polar
coordinates. Use a ufunc!
- Create a random 5 × 10 array and subtract the mean of
each row.
- Now z-transform each column.
- ndarrays have an attribute that determines whether they
are writable. Find out how to make an array read-only!
- Compute bootstrapped 95% confidence intervals for the
mean of a 1D array X (i.e., resample the elements of an
array with replacement N times, compute the mean of
each sample, and then compute percentiles over the
means). Use np.randon.randn to create a 1D array with
100 random values for which to calculate the
bootstrapped 95% CI.


In [157]:
test = np.random.randn(100)

In [154]:
means = []
for i in range(1000):
    means.append(np.random.choice(test, size=100).mean())

In [158]:
test.mean()

0.021993865551463595

In [153]:
np.random.choice?

Docstring:
choice(a, size=None, replace=True, p=None)

Generates a random sample from a given 1-D array

        .. versionadded:: 1.7.0

Parameters
-----------
a : 1-D array-like or int
    If an ndarray, a random sample is generated from its elements.
    If an int, the random sample is generated as if a were np.arange(a)
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
replace : boolean, optional
    Whether the sample is with or without replacement
p : 1-D array-like, optional
    The probabilities associated with each entry in a.
    If not given the sample assumes a uniform distribution over all
    entries in a.

Returns
--------
samples : single item or ndarray
    The generated random samples

Raises
-------
ValueError
    If a is an int and less than zero, if a or p are not 1-dimensional,
    if a is an array-like of siz

In [159]:
bootstrap = test[np.random.randint(
    low=0, high=100, size=(100, 1000))]

In [160]:
np.percentile(bootstrap.mean(0), [2.5, 97.5])

array([-0.17013823,  0.21966828])

In [156]:
np.percentile?

Signature: np.percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)
Docstring:
Compute the qth percentile of the data along the specified axis.

Returns the qth percentile(s) of the array elements.

Parameters
----------
a : array_like
    Input array or object that can be converted to an array.
q : float in range of [0,100] (or sequence of floats)
    Percentile to compute, which must be between 0 and 100 inclusive.
axis : {int, sequence of int, None}, optional
    Axis or axes along which the percentiles are computed. The
    default is to compute the percentile(s) along a flattened
    version of the array. A sequence of axes is supported since
    version 1.9.0.
out : ndarray, optional
    Alternative output array in which to place the result. It must
    have the same shape and buffer length as the expected output,
    but the type (of the output) will be cast if necessary.
overwrite_input : bool, optional
    If True, then allow use 

In [143]:
np.percentile?

Signature: np.percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)
Docstring:
Compute the qth percentile of the data along the specified axis.

Returns the qth percentile(s) of the array elements.

Parameters
----------
a : array_like
    Input array or object that can be converted to an array.
q : float in range of [0,100] (or sequence of floats)
    Percentile to compute, which must be between 0 and 100 inclusive.
axis : {int, sequence of int, None}, optional
    Axis or axes along which the percentiles are computed. The
    default is to compute the percentile(s) along a flattened
    version of the array. A sequence of axes is supported since
    version 1.9.0.
out : ndarray, optional
    Alternative output array in which to place the result. It must
    have the same shape and buffer length as the expected output,
    but the type (of the output) will be cast if necessary.
overwrite_input : bool, optional
    If True, then allow use 

In [129]:
test[0] = 10

ValueError: assignment destination is read-only

In [164]:
test = np.array([('Joe', 22), ('Jill', 23)], dtype=[
    ('name', 'U5'), ('age', np.int)])

In [165]:
test['name']

array(['Joe', 'Jill'], dtype='<U5')

In [166]:
test['age']

array([22, 23])